fix save_unweighted_flag by removing the leading '#' in the first line
giotto-ai/pyflagser pull request #69
Opened 2021-04-02 08:31 UTC by flomlo

Currently the first line of a saved unweighted flag reads '# dim 0' whereas `flagser` strictly expects 'dim 0'.

#### What does this implement/fix? Explain your changes.
Adding the `comments=''` paramenter to np.save fixes this. This is done analogously to `save_weighted_flag`

#### Any other comments?
We did not observe this error before as `load_unweighted_flag` ignores the first line and does not strictly check if it is `dim 0`.
One could "fix" that as well?

2021-04-26 08:49 UTC, ulupo requested changes
Just a linting suggestion here! Otherwise LGTM

2021-04-26 08:49 UTC, ulupo commented on pyflagser/flagio.py
> +                header='dim 0', fmt='%i')
```suggestion
        np.savetxt(f, vertices.reshape((1, -1)), delimiter=' ', comments='', 
                   header='dim 0', fmt='%i')
```

2021-04-26 08:50 UTC, ulupo commented
/azp run

2021-04-29 08:19 UTC, flomlo commented
I hope I pressed the right buttons to accept the suggested linting changes :)

2021-04-29 08:25 UTC, ulupo approved these changes

2021-04-29 08:26 UTC, merged